name: SkillsCard
author: TiveCS
version: 1.0
api-version: 1.13
main: team.creativecode.skillscard.Main
commands:
    skillscard:
        aliases: [skill, skills, scard]
        permission: skillscard